apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          imagePullPolicy: Always
          image: hieucanguyen/bike_share_web_app:1.0
          command: ["python3", "worker.py"]
          env:
           - name: LOG_LEVEL
             value: DEBUG
