---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
          - ./data:/data
        user: "1000:1000"
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - redis-db
        environment:
          - REDIS_DB_SERVICE_SERVICE_HOST=redis-db
          - LOG_LEVEL=DEBUG
        image: hieucanguyen/bike_share_web_app:1.0
        ports:
            - 5000:5000
        command: ["python3", "bike_share_api.py"]
    worker:
      build:
        context: ./
        dockerfile: Dockerfile
      depends_on:
        - redis-db
      environment:
        - REDIS_DB_SERVICE_SERVICE_HOST=redis-db
        - LOG_LEVEL=DEBUG
      command: ["python3", "-u", "worker.py"]
                  
